function [GenPlant, Win, Wout] = generateGenPlant(Plant, Wu, We, W1, W2)
    Wout = blkdiag(Wu, We, eye(size(Plant, 1)));
    Win = blkdiag(W1, W2, eye(size(Plant, 2)));
    GenPlant = Wout * [zeros(size(Plant)) zeros(size(Plant)) eye(size(Plant));
                       eye(size(Plant))  -Plant              -Plant;
                       eye(size(Plant))  -Plant              -Plant;] * Win;
    
    Win.InputName = {'M_d Reference', 'M_q Reference', ...
                     '\beta_d Disturbance', '\beta_q Disturbance', ...
                     '\beta_d Control Input', '\beta_q Control Input'};

    Wout.OutputName = {'Weighted \beta_d Control Input', 'Weighted \beta_q Control Input', ...
                       'Weighted M_d Tracking Error', 'Weighted M_q Tracking Error', ...
                       'Measured M_d Tracking Error', 'Measured M_q Tracking Error'};

    GenPlant.InputName = {'M_d Reference', 'M_q Reference', ...
                          '\beta_d Disturbance', '\beta_q Disturbance', ...
                          '\beta_d Control Input', '\beta_q Control Input'};

    GenPlant.OutputName = {...
        'Weighted \beta_d Control Input', 'Weighted \beta_q Control Input', ...
        'Weighted M_d Tracking Error', 'Weighted M_q Tracking Error', ...
        'Measured M_d Tracking Error', 'Measured M_q Tracking Error'};
end